<?php
/*
 * @file
 * Patterns Client module.
 *
 */

module_load_include('inc', 'patterns_client', 'includes/constants');
module_load_include('inc', 'patterns_client', 'includes/config');
module_load_include('inc', 'patterns_client', 'includes/io');
//module_load_include('inc', 'patterns_client', 'includes/rpc');

/**
 * Implements hook_help().
 */
function patterns_client_help($path,$arg) {
  switch ($path) {
    case "admin/help#patterns_client":
      return '<p>'.t("help for patterns_client module").'<p>';
      break;
  }
}

/**
 * Implements hook_menu().
 */
function patterns_client_menu() {
  // This is the client form menu entry. This form is used to allow user
  // interaction with the services, but again, user interface is not required
  // to create an XML-RPC client with Drupal.
  
  //Add new tab to list patterns stored in the server
  $items['admin/patterns/import/patterns-server'] = array(
      'title' => 'Patterns at Patterns Server',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('_patterns_client_get_patterns_server_list'),
      'access arguments' => array('administer patterns'),
      'type' => MENU_LOCAL_TASK,
  );
  return $items;
}


/**
 * Implements hook_permission().
 */
function patterns_client_permission() {
  return array(
    'access patterns_client' => array(
      'title' => t('Access permission for the patterns_client module'),
      )
    );
}

/**
 * Implements hook_menu_alter().
 */
function patterns_client_menu_alter(&$items) {
  $items['admin/patterns/share'] = array(
    'title' => 'Share',
    'page callback' => 'patterns_client_config',
    'access arguments' => array('administer patterns'),
    'type' => MENU_LOCAL_TASK,
    'weight' => 9,
  );
  return $items;
}

function patterns_client_patterns_publish($pattern) {
  if (variable_get('patterns_client_auto_publish', FALSE)) {
    patterns_client_push_patterns(array($pattern));
  }
  else {
    drupal_set_message(t('Automatic publishing of patterns not enabled.'), 'warning');
  }
}
